[package]
name = "thegrep"
version = "1.0.0"
authors = ["Shannon Goad and Sarah Bost sbost99@cs.unc.edu and sgoad13@live.unc.edu"]
edition = "2018"

[dependencies]
structopt = {version = "0.2"}
rand = "0.6"
